Repository xbmc/repo-plugins, pull requests merged in 2021-02, with the labels that each got.

#3352 [plugin.video.vrt.nu@krypton] 2.4.5
  plugin.video.vrt.nu/README.md
  plugin.video.vrt.nu/addon.xml
  plugin.video.vrt.nu/resources/language/resource.language.en_gb/strings.po
  plugin.video.vrt.nu/resources/language/resource.language.nl_nl/strings.po
  plugin.video.vrt.nu/resources/lib/streamservice.py
  plugin.video.vrt.nu/resources/lib/vrtplayer.py
Labels: Merge on next repo sync

#3356 [plugin.video.rtpplay@krypton] 5.0.11
  plugin.video.rtpplay/addon.xml
  plugin.video.rtpplay/resources/lib/channels.py
  plugin.video.rtpplay/resources/lib/plugin.py
Labels: Merge on next repo sync

#3359 [plugin.video.hbogoeu@leia] 2.6.3
  plugin.video.hbogoeu/README.md
  plugin.video.hbogoeu/addon.xml
  plugin.video.hbogoeu/hbogolib/handler.py
  plugin.video.hbogoeu/hbogolib/handlersp.py
  plugin.video.hbogoeu/resources/language/resource.language.pl_pl/strings.po
Labels: Merge on next repo sync

#3345 [plugin.video.streamz@leia] 1.0.5
  plugin.video.streamz/CHANGELOG.md
  plugin.video.streamz/README.md
  plugin.video.streamz/addon.xml
  plugin.video.streamz/resources/language/resource.language.en_gb/strings.po
  plugin.video.streamz/resources/language/resource.language.nl_nl/strings.po
  plugin.video.streamz/resources/lib/modules/catalog.py
  plugin.video.streamz/resources/lib/modules/library.py
  plugin.video.streamz/resources/lib/modules/menu.py
  plugin.video.streamz/resources/lib/modules/player.py
  plugin.video.streamz/resources/lib/modules/search.py
  plugin.video.streamz/resources/lib/streamz/__init__.py
  plugin.video.streamz/resources/lib/streamz/api.py
  plugin.video.streamz/resources/lib/streamz/exceptions.py
  plugin.video.streamz/resources/settings.xml
Labels: Merge on next repo sync

#3348 [plugin.video.vtm.go@leia] 1.2.3
  plugin.video.vtm.go/CHANGELOG.md
  plugin.video.vtm.go/addon.xml
  plugin.video.vtm.go/resources/lib/addon.py
  plugin.video.vtm.go/resources/lib/kodiutils.py
  plugin.video.vtm.go/resources/lib/modules/menu.py
  plugin.video.vtm.go/resources/lib/modules/player.py
  plugin.video.vtm.go/resources/lib/modules/proxy.py
  plugin.video.vtm.go/resources/lib/service.py
  plugin.video.vtm.go/resources/lib/vtmgo/util.py
  plugin.video.vtm.go/resources/lib/vtmgo/vtmgo.py
  plugin.video.vtm.go/resources/lib/vtmgo/vtmgoauth.py
  plugin.video.vtm.go/resources/lib/vtmgo/vtmgostream.py
Labels: Merge on next repo sync

#3337 [plugin.video.catchuptvandmore] 0.2.29
  plugin.video.catchuptvandmore/addon.xml
  plugin.video.catchuptvandmore/resources/lib/channels/be/rtbf.py
  plugin.video.catchuptvandmore/resources/lib/channels/be/rtc.py
  plugin.video.catchuptvandmore/resources/lib/channels/be/telemb.py
  plugin.video.catchuptvandmore/resources/lib/channels/fr/6play.py
  plugin.video.catchuptvandmore/resources/lib/channels/fr/bsmart.py
  plugin.video.catchuptvandmore/resources/lib/channels/fr/gulli.py
  plugin.video.catchuptvandmore/resources/lib/channels/fr/lci.py
  plugin.video.catchuptvandmore/resources/lib/channels/fr/mytf1.py
  plugin.video.catchuptvandmore/resources/lib/channels/wo/arte.py
  plugin.video.catchuptvandmore/resources/lib/main.py
  plugin.video.catchuptvandmore/resources/lib/skeletons/fr_live.py
  plugin.video.catchuptvandmore/resources/lib/skeletons/fr_replay.py
  plugin.video.catchuptvandmore/resources/m3u/live_tv_all.m3u
  plugin.video.catchuptvandmore/resources/m3u/live_tv_fr.m3u
Labels: waiting for developer to respond

#3363 [plugin.video.rtpplay@krypton] 5.0.12
  plugin.video.rtpplay/addon.xml
  plugin.video.rtpplay/resources/language/resource.language.en_gb/strings.po
  plugin.video.rtpplay/resources/language/resource.language.pt_pt/strings.po
  plugin.video.rtpplay/resources/lib/plugin.py
Labels: Merge on next repo sync

#3374 [plugin.video.zdf_de_lite] v5.0.2
  plugin.video.zdf_de_lite/addon.xml
  plugin.video.zdf_de_lite/default.py
Labels: Merge on next repo sync

#3380 [plugin.video.videomediaset@matrix] 2.0.2+matrix.1
  plugin.video.videomediaset/LICENSE.txt
  plugin.video.videomediaset/addon.xml
  plugin.video.videomediaset/changelog.txt
  plugin.video.videomediaset/default.py
  plugin.video.videomediaset/resources/__init__.py
  plugin.video.videomediaset/resources/fanart.jpg
  plugin.video.videomediaset/resources/icon.png
  plugin.video.videomediaset/resources/language/resource.language.en_gb/strings.po
  plugin.video.videomediaset/resources/language/resource.language.it_it/strings.po
  plugin.video.videomediaset/resources/lib/__init__.py
  plugin.video.videomediaset/resources/lib/mediaset.py
  plugin.video.videomediaset/resources/main.py
  plugin.video.videomediaset/resources/mediaset_datahelper.py
  plugin.video.videomediaset/resources/settings.xml
Labels: Merge on next repo sync

#3369 [plugin.video.francetv] 2.0.1
  plugin.video.francetv/addon.xml
  plugin.video.francetv/resources/lib/addon.py
  plugin.video.francetv/resources/lib/api.py
  plugin.video.francetv/resources/media/culturebox.png
  plugin.video.francetv/resources/media/next-page.png
Labels: Merge on next repo sync

#3385 [plugin.video.eitb] 2.0.0
  plugin.video.eitb/LICENSE.txt
  plugin.video.eitb/README.md
  plugin.video.eitb/README_es.md
  plugin.video.eitb/README_eu.md
  plugin.video.eitb/addon.py
  plugin.video.eitb/addon.xml
  plugin.video.eitb/audio.py
  plugin.video.eitb/changelog.txt
  plugin.video.eitb/fanart.jpg
  plugin.video.eitb/icon.png
  plugin.video.eitb/utils.py
  plugin.video.eitb/video.py
Labels: waiting for developer to respond

#3403 [plugin.video.viervijfzes@matrix] 0.4.1+matrix.1
  plugin.video.viervijfzes/CHANGELOG.md
  plugin.video.viervijfzes/LICENSE
  plugin.video.viervijfzes/README.md
  plugin.video.viervijfzes/addon.xml
  plugin.video.viervijfzes/addon_entry.py
  plugin.video.viervijfzes/resources/__init__.py
  plugin.video.viervijfzes/resources/fanart.png
  plugin.video.viervijfzes/resources/icon.png
  plugin.video.viervijfzes/resources/language/resource.language.en_gb/strings.po
  plugin.video.viervijfzes/resources/language/resource.language.nl_nl/strings.po
  plugin.video.viervijfzes/resources/lib/__init__.py
  plugin.video.viervijfzes/resources/lib/addon.py
  plugin.video.viervijfzes/resources/lib/kodilogging.py
  plugin.video.viervijfzes/resources/lib/kodiutils.py
  plugin.video.viervijfzes/resources/lib/modules/__init__.py
  plugin.video.viervijfzes/resources/lib/modules/catalog.py
  plugin.video.viervijfzes/resources/lib/modules/channels.py
  plugin.video.viervijfzes/resources/lib/modules/iptvmanager.py
  plugin.video.viervijfzes/resources/lib/modules/menu.py
  plugin.video.viervijfzes/resources/lib/modules/player.py
  plugin.video.viervijfzes/resources/lib/modules/search.py
  plugin.video.viervijfzes/resources/lib/modules/tvguide.py
  plugin.video.viervijfzes/resources/lib/service.py
  plugin.video.viervijfzes/resources/lib/viervijfzes/__init__.py
  plugin.video.viervijfzes/resources/lib/viervijfzes/auth.py
  plugin.video.viervijfzes/resources/lib/viervijfzes/aws/__init__.py
  plugin.video.viervijfzes/resources/lib/viervijfzes/aws/cognito_identity.py
  plugin.video.viervijfzes/resources/lib/viervijfzes/aws/cognito_idp.py
  plugin.video.viervijfzes/resources/lib/viervijfzes/aws/cognito_sync.py
  plugin.video.viervijfzes/resources/lib/viervijfzes/content.py
  plugin.video.viervijfzes/resources/lib/viervijfzes/epg.py
  plugin.video.viervijfzes/resources/lib/viervijfzes/search.py
  plugin.video.viervijfzes/resources/logos/goplay-background.png
  plugin.video.viervijfzes/resources/logos/goplay.png
  plugin.video.viervijfzes/resources/logos/play4-background.png
  plugin.video.viervijfzes/resources/logos/play4.png
  plugin.video.viervijfzes/resources/logos/play5-background.png
  plugin.video.viervijfzes/resources/logos/play5.png
  plugin.video.viervijfzes/resources/logos/play6-background.png
  plugin.video.viervijfzes/resources/logos/play6.png
  plugin.video.viervijfzes/resources/screenshot01.jpg
  plugin.video.viervijfzes/resources/screenshot02.jpg
  plugin.video.viervijfzes/resources/screenshot03.jpg
  plugin.video.viervijfzes/resources/settings.xml
  plugin.video.viervijfzes/service_entry.py
Labels: waiting for secondary review
