Repository xbmc/repo-plugins, pull requests merged in 2022-10, with the labels that each got.

#4125 [plugin.video.twitch@matrix] 2.6.2+matrix.1
  plugin.video.twitch/addon.xml
  plugin.video.twitch/resources/language/resource.language.ca_es/strings.po
  plugin.video.twitch/resources/language/resource.language.da_dk/strings.po
  plugin.video.twitch/resources/language/resource.language.fi_fi/strings.po
  plugin.video.twitch/resources/language/resource.language.it_it/strings.po
  plugin.video.twitch/resources/language/resource.language.ko_kr/strings.po
  plugin.video.twitch/resources/language/resource.language.nl_nl/strings.po
  plugin.video.twitch/resources/language/resource.language.ru_ru/strings.po
Labels: hacktoberfest-accepted

#4118 [plugin.video.nhklive] 4.0.8
  plugin.video.nhklive/README.txt
  plugin.video.nhklive/addon.xml
  plugin.video.nhklive/resources/lib/scraper.py
Labels: hacktoberfest-accepted

#4120 [plugin.video.youtube@matrix] 6.8.20+matrix.1
  plugin.video.youtube/addon.xml
  plugin.video.youtube/resources/language/resource.language.be_by/strings.po
  plugin.video.youtube/resources/language/resource.language.cs_cz/strings.po
  plugin.video.youtube/resources/language/resource.language.da_dk/strings.po
  plugin.video.youtube/resources/language/resource.language.en_us/strings.po
  plugin.video.youtube/resources/language/resource.language.es_es/strings.po
  plugin.video.youtube/resources/language/resource.language.es_mx/strings.po
  plugin.video.youtube/resources/language/resource.language.fi_fi/strings.po
  plugin.video.youtube/resources/language/resource.language.fr_fr/strings.po
  plugin.video.youtube/resources/language/resource.language.he_il/strings.po
  plugin.video.youtube/resources/language/resource.language.hr_hr/strings.po
  plugin.video.youtube/resources/language/resource.language.it_it/strings.po
  plugin.video.youtube/resources/language/resource.language.nb_no/strings.po
  plugin.video.youtube/resources/language/resource.language.nl_nl/strings.po
  plugin.video.youtube/resources/language/resource.language.pt_br/strings.po
  plugin.video.youtube/resources/language/resource.language.pt_pt/strings.po
  plugin.video.youtube/resources/language/resource.language.ro_md/strings.po
  plugin.video.youtube/resources/language/resource.language.ro_ro/strings.po
  plugin.video.youtube/resources/language/resource.language.ru_ru/strings.po
  plugin.video.youtube/resources/language/resource.language.scn/strings.po
  plugin.video.youtube/resources/language/resource.language.sk_sk/strings.po
  plugin.video.youtube/resources/language/resource.language.sv_se/strings.po
  plugin.video.youtube/resources/language/resource.language.vi_vn/strings.po
  plugin.video.youtube/resources/language/resource.language.zh_cn/strings.po
  plugin.video.youtube/resources/language/resource.language.zh_tw/strings.po
  plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_context_ui.py
  plugin.video.youtube/resources/lib/youtube_plugin/kodion/json_store/json_store.py
  plugin.video.youtube/resources/lib/youtube_plugin/kodion/utils/http_server.py
  plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/subtitles.py
  plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/url_resolver.py
  plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/url_to_item_converter.py
  plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py
Labels: hacktoberfest-accepted

#4124 [plugin.video.twitch@isengard] 2.6.2
  plugin.video.twitch/addon.xml
  plugin.video.twitch/resources/language/resource.language.ca_es/strings.po
  plugin.video.twitch/resources/language/resource.language.da_dk/strings.po
  plugin.video.twitch/resources/language/resource.language.fi_fi/strings.po
  plugin.video.twitch/resources/language/resource.language.it_it/strings.po
  plugin.video.twitch/resources/language/resource.language.ko_kr/strings.po
  plugin.video.twitch/resources/language/resource.language.nl_nl/strings.po
  plugin.video.twitch/resources/language/resource.language.ru_ru/strings.po
Labels: Merge on next repo sync, hacktoberfest-accepted

#4119 [plugin.video.youtube@isengard] 6.8.20
  plugin.video.youtube/addon.xml
  plugin.video.youtube/changelog.txt
  plugin.video.youtube/resources/language/resource.language.be_by/strings.po
  plugin.video.youtube/resources/language/resource.language.cs_cz/strings.po
  plugin.video.youtube/resources/language/resource.language.da_dk/strings.po
  plugin.video.youtube/resources/language/resource.language.en_us/strings.po
  plugin.video.youtube/resources/language/resource.language.es_es/strings.po
  plugin.video.youtube/resources/language/resource.language.es_mx/strings.po
  plugin.video.youtube/resources/language/resource.language.fi_fi/strings.po
  plugin.video.youtube/resources/language/resource.language.fr_fr/strings.po
  plugin.video.youtube/resources/language/resource.language.he_il/strings.po
  plugin.video.youtube/resources/language/resource.language.hr_hr/strings.po
  plugin.video.youtube/resources/language/resource.language.it_it/strings.po
  plugin.video.youtube/resources/language/resource.language.nb_no/strings.po
  plugin.video.youtube/resources/language/resource.language.nl_nl/strings.po
  plugin.video.youtube/resources/language/resource.language.pt_br/strings.po
  plugin.video.youtube/resources/language/resource.language.pt_pt/strings.po
  plugin.video.youtube/resources/language/resource.language.ro_md/strings.po
  plugin.video.youtube/resources/language/resource.language.ro_ro/strings.po
  plugin.video.youtube/resources/language/resource.language.ru_ru/strings.po
  plugin.video.youtube/resources/language/resource.language.scn/strings.po
  plugin.video.youtube/resources/language/resource.language.sk_sk/strings.po
  plugin.video.youtube/resources/language/resource.language.sv_se/strings.po
  plugin.video.youtube/resources/language/resource.language.vi_vn/strings.po
  plugin.video.youtube/resources/language/resource.language.zh_cn/strings.po
  plugin.video.youtube/resources/language/resource.language.zh_tw/strings.po
  plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_context_ui.py
  plugin.video.youtube/resources/lib/youtube_plugin/kodion/json_store/json_store.py
  plugin.video.youtube/resources/lib/youtube_plugin/kodion/utils/http_server.py
  plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/subtitles.py
  plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/url_resolver.py
  plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/url_to_item_converter.py
  plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py
Labels: hacktoberfest-accepted

#4121 [plugin.video.composite_for_plex@leia] 1.4.3
  plugin.video.composite_for_plex/addon.xml
  plugin.video.composite_for_plex/resources/language/resource.language.be_by/strings.po
  plugin.video.composite_for_plex/resources/language/resource.language.bg_bg/strings.po
  plugin.video.composite_for_plex/resources/language/resource.language.ca_es/strings.po
  plugin.video.composite_for_plex/resources/language/resource.language.cs_cz/strings.po
  plugin.video.composite_for_plex/resources/language/resource.language.da_dk/strings.po
  plugin.video.composite_for_plex/resources/language/resource.language.el_gr/strings.po
  plugin.video.composite_for_plex/resources/language/resource.language.en_us/strings.po
  plugin.video.composite_for_plex/resources/language/resource.language.es_es/strings.po
  plugin.video.composite_for_plex/resources/language/resource.language.fi_fi/strings.po
  plugin.video.composite_for_plex/resources/language/resource.language.fr_fr/strings.po
  plugin.video.composite_for_plex/resources/language/resource.language.he_il/strings.po
  plugin.video.composite_for_plex/resources/language/resource.language.hr_hr/strings.po
  plugin.video.composite_for_plex/resources/language/resource.language.hu_hu/strings.po
  plugin.video.composite_for_plex/resources/language/resource.language.it_it/strings.po
  plugin.video.composite_for_plex/resources/language/resource.language.ko_kr/strings.po
  plugin.video.composite_for_plex/resources/language/resource.language.nb_no/strings.po
  plugin.video.composite_for_plex/resources/language/resource.language.nl_nl/strings.po
  plugin.video.composite_for_plex/resources/language/resource.language.pl_pl/strings.po
  plugin.video.composite_for_plex/resources/language/resource.language.pt_br/strings.po
  plugin.video.composite_for_plex/resources/language/resource.language.pt_pt/strings.po
  plugin.video.composite_for_plex/resources/language/resource.language.ro_md/strings.po
  plugin.video.composite_for_plex/resources/language/resource.language.ro_ro/strings.po
  plugin.video.composite_for_plex/resources/language/resource.language.ru_ru/strings.po
  plugin.video.composite_for_plex/resources/language/resource.language.scn/strings.po
  plugin.video.composite_for_plex/resources/language/resource.language.sk_sk/strings.po
  plugin.video.composite_for_plex/resources/language/resource.language.sv_se/strings.po
  plugin.video.composite_for_plex/resources/language/resource.language.tr_tr/strings.po
  plugin.video.composite_for_plex/resources/language/resource.language.uk_ua/strings.po
  plugin.video.composite_for_plex/resources/language/resource.language.vi_vn/strings.po
  plugin.video.composite_for_plex/resources/language/resource.language.zh_cn/strings.po
  plugin.video.composite_for_plex/resources/language/resource.language.zh_tw/strings.po
  plugin.video.composite_for_plex/resources/lib/composite_addon/routes/configure_library_sections.py
Labels: hacktoberfest-accepted

#4129 [plugin.video.vrt.nu@krypton] 2.5.18
  plugin.video.vrt.nu/README.md
  plugin.video.vrt.nu/addon.xml
  plugin.video.vrt.nu/resources/lib/addon.py
  plugin.video.vrt.nu/resources/lib/api.py
  plugin.video.vrt.nu/resources/lib/apihelper.py
  plugin.video.vrt.nu/resources/lib/playerinfo.py
  plugin.video.vrt.nu/resources/lib/search.py
  plugin.video.vrt.nu/resources/lib/vrtplayer.py
Labels: Merge on next repo sync

#4127 [plugin.video.montreal.greek-tv] 4.0.1
  plugin.video.montreal.greek-tv/addon.py
  plugin.video.montreal.greek-tv/addon.xml
  plugin.video.montreal.greek-tv/resources/art/montreal_background.jpg
  plugin.video.montreal.greek-tv/resources/lib/default.py
  plugin.video.montreal.greek-tv/resources/settings.xml
Labels: Approved

#4136 [plugin.video.vrt.nu@krypton] 2.5.19
  plugin.video.vrt.nu/README.md
  plugin.video.vrt.nu/addon.xml
  plugin.video.vrt.nu/resources/language/resource.language.en_gb/strings.po
  plugin.video.vrt.nu/resources/language/resource.language.nl_nl/strings.po
  plugin.video.vrt.nu/resources/lib/addon.py
  plugin.video.vrt.nu/resources/lib/api.py
  plugin.video.vrt.nu/resources/lib/graphql_data.py
  plugin.video.vrt.nu/resources/lib/playerinfo.py
  plugin.video.vrt.nu/resources/lib/resumepoints.py
  plugin.video.vrt.nu/resources/lib/streamservice.py
  plugin.video.vrt.nu/resources/lib/vrtplayer.py
Labels: Merge on next repo sync
