Repository xbmc/repo-plugins, pull requests merged in 2022-08, with the labels that each got.

#4079 [plugin.video.orftvthek] 0.12.5+matrix.1
  plugin.video.orftvthek/addon.xml
  plugin.video.orftvthek/changelog.txt
  plugin.video.orftvthek/resources/lib/Addon.py
  plugin.video.orftvthek/resources/lib/HtmlScraper.py
Labels: Approved

#4077 [plugin.video.vrt.nu@krypton] 2.5.13
  plugin.video.vrt.nu/README.md
  plugin.video.vrt.nu/addon.xml
  plugin.video.vrt.nu/resources/lib/apihelper.py
  plugin.video.vrt.nu/resources/lib/kodiutils.py
  plugin.video.vrt.nu/resources/lib/streamservice.py
  plugin.video.vrt.nu/resources/lib/tokenresolver.py
  plugin.video.vrt.nu/resources/media/screenshot01.jpg
  plugin.video.vrt.nu/resources/media/screenshot02.jpg
  plugin.video.vrt.nu/resources/media/screenshot03.jpg
  plugin.video.vrt.nu/resources/media/screenshot04.jpg
Labels: Approved

#4075 [plugin.video.imdb.trailers] 2.1.16+matrix.1
  plugin.video.imdb.trailers/addon.xml
  plugin.video.imdb.trailers/default.py
  plugin.video.imdb.trailers/resources/images/screenshot-01.jpg
  plugin.video.imdb.trailers/resources/images/screenshot-02.jpg
  plugin.video.imdb.trailers/resources/images/screenshot-03.jpg
  plugin.video.imdb.trailers/resources/images/screenshot-04.jpg
  plugin.video.imdb.trailers/resources/lib/client.py
  plugin.video.imdb.trailers/resources/lib/imdb_trailers.py
  plugin.video.imdb.trailers/resources/settings.xml
Labels: Approved

#4074 [plugin.video.teliaplay-se] v1.2.5+matrix.1
  plugin.video.teliaplay-se/Changelog.txt
  plugin.video.teliaplay-se/addon.xml
  plugin.video.teliaplay-se/resources/lib/api.py
  plugin.video.teliaplay-se/resources/lib/menus.py
Labels: Approved

#4083 [plugin.video.imdb.trailers] 2.1.16
  plugin.video.imdb.trailers/addon.xml
  plugin.video.imdb.trailers/default.py
  plugin.video.imdb.trailers/resources/images/screenshot-01.jpg
  plugin.video.imdb.trailers/resources/images/screenshot-02.jpg
  plugin.video.imdb.trailers/resources/images/screenshot-03.jpg
  plugin.video.imdb.trailers/resources/images/screenshot-04.jpg
  plugin.video.imdb.trailers/resources/lib/client.py
  plugin.video.imdb.trailers/resources/lib/imdb_trailers.py
  plugin.video.imdb.trailers/resources/settings.xml
Labels: Approved

#4093 [plugin.video.vrt.nu@krypton] 2.5.14
  plugin.video.vrt.nu/README.md
  plugin.video.vrt.nu/addon.xml
  plugin.video.vrt.nu/channels.m3u8
  plugin.video.vrt.nu/resources/language/resource.language.en_gb/strings.po
  plugin.video.vrt.nu/resources/language/resource.language.nl_nl/strings.po
  plugin.video.vrt.nu/resources/lib/addon.py
  plugin.video.vrt.nu/resources/lib/addon_entry.py
  plugin.video.vrt.nu/resources/lib/apihelper.py
  plugin.video.vrt.nu/resources/lib/data.py
  plugin.video.vrt.nu/resources/lib/favorites.py
  plugin.video.vrt.nu/resources/lib/helperobjects.py
  plugin.video.vrt.nu/resources/lib/kodiutils.py
  plugin.video.vrt.nu/resources/lib/metadata.py
  plugin.video.vrt.nu/resources/lib/playerinfo.py
  plugin.video.vrt.nu/resources/lib/resumepoints.py
  plugin.video.vrt.nu/resources/lib/search.py
  plugin.video.vrt.nu/resources/lib/service.py
  plugin.video.vrt.nu/resources/lib/service_entry.py
  plugin.video.vrt.nu/resources/lib/streamservice.py
  plugin.video.vrt.nu/resources/lib/tokenresolver.py
  plugin.video.vrt.nu/resources/lib/tvguide.py
  plugin.video.vrt.nu/resources/lib/utils.py
  plugin.video.vrt.nu/resources/lib/vrtplayer.py
  plugin.video.vrt.nu/resources/lib/webscraper.py
  plugin.video.vrt.nu/resources/media/screenshot01.jpg
  plugin.video.vrt.nu/resources/media/screenshot02.jpg
  plugin.video.vrt.nu/resources/media/screenshot03.jpg
  plugin.video.vrt.nu/resources/media/screenshot04.jpg
  plugin.video.vrt.nu/resources/settings.xml
Labels: Merge on next repo sync

#4047 [plugin.program.autocompletion@matrix] 2.0.5
  plugin.program.autocompletion/addon.xml
  plugin.program.autocompletion/plugin.py
  plugin.program.autocompletion/resources/language/resource.language.en_gb/strings.po
  plugin.program.autocompletion/resources/language/resource.language.es_es/strings.po
  plugin.program.autocompletion/resources/language/resource.language.fr_fr/strings.po
  plugin.program.autocompletion/resources/language/resource.language.he_il/strings.po
  plugin.program.autocompletion/resources/language/resource.language.it_it/strings.po
  plugin.program.autocompletion/resources/settings.xml
Labels: waiting for developer to respond
