Repository xbmc/repo-plugins, pull requests merged in 2023-07, with the labels that each got.

#4345 [plugin.video.svtplay@matrix] 5.1.18+matrix.1
  plugin.video.svtplay/addon.xml
  plugin.video.svtplay/resources/lib/api/graphql.py
Labels: Approved

#4346 [plugin.video.mlbtv@matrix] 2023.6.24+matrix.1
  plugin.video.mlbtv/addon.xml
  plugin.video.mlbtv/resources/lib/account.py
  plugin.video.mlbtv/service.py
Labels: Approved

#4348 [plugin.video.vrt.nu@matrix] 2.5.23+matrix.1
  plugin.video.vrt.nu/README.md
  plugin.video.vrt.nu/addon.xml
  plugin.video.vrt.nu/resources/lib/api.py
Labels: Approved

#4349 [plugin.video.vrt.nu@krypton] 2.5.23
  plugin.video.vrt.nu/README.md
  plugin.video.vrt.nu/addon.xml
  plugin.video.vrt.nu/resources/lib/api.py
Labels: Merge on next repo sync, Approved

#4344 [plugin.video.svtplay@krypton] 5.1.18
  plugin.video.svtplay/addon.xml
  plugin.video.svtplay/resources/lib/api/graphql.py
Labels: waiting for dependency to be merged

#4352 [plugin.video.vrt.nu@krypton] 2.5.24
  plugin.video.vrt.nu/README.md
  plugin.video.vrt.nu/addon.xml
  plugin.video.vrt.nu/resources/lib/playerinfo.py
  plugin.video.vrt.nu/resources/lib/streamservice.py
  plugin.video.vrt.nu/resources/lib/tokenresolver.py
  plugin.video.vrt.nu/resources/lib/utils.py
Labels: Merge on next repo sync
