Repository xbmc/repo-plugins, pull requests merged in 2023-09, with the labels that each got.

#4367 [plugin.video.imdb.trailers] 2.1.18
  plugin.video.imdb.trailers/addon.xml
  plugin.video.imdb.trailers/resources/lib/cache.py
  plugin.video.imdb.trailers/resources/lib/client.py
  plugin.video.imdb.trailers/resources/lib/imdb_trailers.py
Labels: Merge on next repo sync, Approved

#4370 [plugin.video.orftvthek] 0.12.9+matrix.1
  plugin.video.orftvthek/README.md
  plugin.video.orftvthek/addon.xml
  plugin.video.orftvthek/changelog.txt
  plugin.video.orftvthek/resources/lib/Addon.py
  plugin.video.orftvthek/resources/lib/HtmlScraper.py
  plugin.video.orftvthek/resources/lib/Scraper.py
  plugin.video.orftvthek/resources/lib/ServiceApi.py
Labels: Approved

#4372 [plugin.video.svtplay@krypton] 5.1.19
  plugin.video.svtplay/addon.xml
  plugin.video.svtplay/resources/language/resource.language.en_gb/strings.po
  plugin.video.svtplay/resources/language/resource.language.sv_se/strings.po
  plugin.video.svtplay/resources/lib/api/graphql.py
  plugin.video.svtplay/resources/lib/svtplay.py
Labels: Merge on next repo sync, Approved

#4363 [plugin.video.invidious] 0.2.2+nexus.0
  plugin.video.invidious/LICENSE.txt
  plugin.video.invidious/README.md
  plugin.video.invidious/addon.xml
  plugin.video.invidious/resources/fanart.png
  plugin.video.invidious/resources/icon.png
  plugin.video.invidious/resources/language/README
  plugin.video.invidious/resources/language/resource.language.en_gb/strings.po
  plugin.video.invidious/resources/language/resource.language.nb_no/strings.po
  plugin.video.invidious/resources/lib/invidious_addon.py
  plugin.video.invidious/resources/lib/invidious_api.py
  plugin.video.invidious/resources/lib/invidious_plugin.py
  plugin.video.invidious/resources/settings.xml
Labels: Approved

#4371 [plugin.video.twitch@nexus] 3.0.2
  plugin.video.twitch/addon.xml
  plugin.video.twitch/resources/language/resource.language.ca_es/strings.po
  plugin.video.twitch/resources/language/resource.language.es_es/strings.po
  plugin.video.twitch/resources/language/resource.language.fr_fr/strings.po
  plugin.video.twitch/resources/language/resource.language.it_it/strings.po
  plugin.video.twitch/resources/lib/twitch_addon/addon/api.py
  plugin.video.twitch/resources/lib/twitch_addon/routes/followed.py
Labels: Approved, waiting for dependency to be merged

#4383 [plugin.video.retrospect] v5.6.5
  plugin.video.retrospect/README.md
  plugin.video.retrospect/addon.xml
  plugin.video.retrospect/channels/channel.nick/nickelodeon/chn_nickelodeon.py
  plugin.video.retrospect/channels/channel.nos/nos2010/chn_nos2010.py
  plugin.video.retrospect/channels/channel.se/svt/chn_svt.py
  plugin.video.retrospect/resources/language/resource.language.ca_es/strings.po
  plugin.video.retrospect/resources/language/resource.language.fi_fi/strings.po
  plugin.video.retrospect/resources/lib/actions/iptvmanageraction.py
  plugin.video.retrospect/resources/lib/streams/npostream.py
Labels: Approved

#4369 [plugin.audio.ampache@matrix] 3.1.0+matrix.1
  plugin.audio.ampache/addon.xml
  plugin.audio.ampache/resources/language/resource.language.it_it/strings.po
  plugin.audio.ampache/resources/lib/ampache_connect.py
  plugin.audio.ampache/resources/lib/ampache_plugin.py
Labels: Approved

#4368 [plugin.video.viwx] 1.0.0
  plugin.video.viwx/LICENSE.txt
  plugin.video.viwx/addon.py
  plugin.video.viwx/addon.xml
  plugin.video.viwx/changelog.txt
  plugin.video.viwx/resources/__init__.py
  plugin.video.viwx/resources/fanart.png
  plugin.video.viwx/resources/icon.png
  plugin.video.viwx/resources/language/resource.language.en_gb/strings.po
  plugin.video.viwx/resources/lib/__init__.py
  plugin.video.viwx/resources/lib/addon_log.py
  plugin.video.viwx/resources/lib/cache.py
  plugin.video.viwx/resources/lib/cc_patch.py
  plugin.video.viwx/resources/lib/errors.py
  plugin.video.viwx/resources/lib/fetch.py
  plugin.video.viwx/resources/lib/itv.py
  plugin.video.viwx/resources/lib/itv_account.py
  plugin.video.viwx/resources/lib/itvx.py
  plugin.video.viwx/resources/lib/kodi_utils.py
  plugin.video.viwx/resources/lib/main.py
  plugin.video.viwx/resources/lib/parsex.py
  plugin.video.viwx/resources/lib/settings.py
  plugin.video.viwx/resources/lib/utils.py
  plugin.video.viwx/resources/settings.xml
Labels: Approved

#4385 [plugin.video.vrt.nu@krypton] 2.5.25
  plugin.video.vrt.nu/README.md
  plugin.video.vrt.nu/addon.xml
  plugin.video.vrt.nu/resources/lib/api.py
Labels: Merge on next repo sync

#4387 [plugin.video.svtplay@krypton] 5.1.21
  plugin.video.svtplay/addon.xml
  plugin.video.svtplay/resources/lib/api/graphql.py
  plugin.video.svtplay/resources/lib/svtplay.py
Labels: Approved

#4391 [plugin.video.vrt.nu@krypton] 2.5.26
  plugin.video.vrt.nu/README.md
  plugin.video.vrt.nu/addon.xml
  plugin.video.vrt.nu/resources/lib/api.py
  plugin.video.vrt.nu/resources/lib/data.py
  plugin.video.vrt.nu/resources/lib/streamservice.py
Labels: Merge on next repo sync, Approved
